# Generated by Django 2.0.7 on 2021-08-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_to_Z', '0004_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='offer',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
