# Generated by Django 2.0.7 on 2021-09-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_to_Z', '0005_shops_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='lovis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshirt', models.ImageField(upload_to='pics')),
                ('shirt', models.ImageField(upload_to='pics')),
                ('pants', models.ImageField(upload_to='pics')),
                ('trending', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
