# Generated by Django 2.0.7 on 2021-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_to_Z', '0006_lovis'),
    ]

    operations = [
        migrations.CreateModel(
            name='lovis1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshirt', models.ImageField(upload_to='pics')),
                ('tshirt_name', models.CharField(max_length=100)),
                ('tshirt_price', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='lovis',
        ),
    ]
