# Generated by Django 2.0.7 on 2021-09-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_to_Z', '0007_auto_20210903_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovis1',
            name='pant',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lovis1',
            name='pant_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lovis1',
            name='pant_price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lovis1',
            name='shirt',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lovis1',
            name='shirt_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lovis1',
            name='shirt_price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
