# Generated by Django 2.0.7 on 2021-09-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_to_Z', '0008_auto_20210907_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='lovis2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name1', models.TextField()),
                ('products_name2', models.TextField()),
                ('products_price', models.IntegerField()),
                ('products_img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
