# Generated by Django 3.2.7 on 2021-09-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('city', models.TextField()),
            ],
        ),
    ]
