# Generated by Django 3.2.7 on 2021-09-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_to_Z', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='trending_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
