# Generated by Django 3.2.7 on 2021-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_to_Z', '0004_products_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
