# Generated by Django 3.2.7 on 2021-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_to_Z', '0005_products_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending_products',
            name='shop_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trending_products',
            name='shop_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
