# Generated by Django 3.2.7 on 2021-09-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_to_Z', '0006_auto_20210916_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='city',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
